# Dependencies
markdown:         kramdown
highlighter:      rouge

# Gems
gems: [jekyll-paginate]

future: true

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Yun Hwan Na
tagline:          'A Jekyll theme'
description:      '디발자 혹은 개자이너'
#url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         2
paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
